---
name: Pytest

defaults:
  run:
    shell: bash

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # run CI every day even if no PRs/merges occur
    - cron: '0 12 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-2022"]
        python: ${{ (github.event_name == 'pull_request' && fromJSON('["3.10", "3.12"]')) || fromJSON('["3.10", "3.11", "3.12"]') }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"
          cache-dependency-path: setup.py
      
      - name: Install dependencies
        run: |
          pip install ".[test]"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

        run: |
          make test